name: mcode
description: A new Flutter Restaurant App project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  path: any
  flutter_svg: ^1.1.0
  flutter_slidable: ^2.0.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  awesome_snackbar_content: ^0.1.0
  firebase_storage: ^11.0.6
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
